/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || "{77431104-EC77-4072-B8F4-DE6FE1C0675E}",
config.sitecoreApiHost = process.env.SITECORE_API_HOST || "https://sc1020xp1cd.local",
config.jssAppName = process.env.JSS_APP_NAME || "nextjs",
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || "/sitecore/api/graph/edge",
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || `${config.sitecoreApiHost}${config.graphQLEndpointPath}`;
module.exports = config;